defaults: &defaults
  working_directory: /tmp

version: 2

jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.36.1
    working_directory: /tmp
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s -t introduction /tmp
      - persist_to_workspace:
          root: /tmp
  deploy:
    docker:
      - image: devillex/docker-firebase
    working_directory: /tmp
    steps:
      - attach_workspace:
          at: /tmp
      - run: firebase --project b6n-website deploy --only hosting

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
