version: 2
jobs:
  one:
    docker:
      - image: felicianotech/docker-hugo:0.21
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ~/project/src/
      - run:
          name: "Test Website"
          command: htmlproofer ~/project/src/public --allow-hash-href --check-html --empty-alt-ignore
  two:
    docker:
      - image: devillex/docker-firebase
    steps:
      - run: firebase --project b6n-website deploy --only hosting

workflows:
  version: 2
  b_and_d:
    jobs:
      - one
      - two:
        requires:
          - one
